name: Notify sekai-nina-site on Push

on:
  push:
    branches:
      - main

jobs:
  trigger-site-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cloudflare Pages Deploy Hook
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/d80d9713-cb69-47e5-aa7d-6e1a939c7305"

      - name: Log deployment trigger
        run: |
          echo "Triggered Cloudflare Pages deployment for sekai-nina-site"
